spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
    show-sql: false

api:
  security:
    token:
      secret: ${JWT_SECRET}
      expiration: 86400000

app:
  admin:
    email: ${ADMIN_EMAIL:}
    password: ${ADMIN_PASSWORD:}