spring:
  application:
    name: notes-api

logging:
  level:
    org:
      springframework:
        security: DEBUG

api:
  security:
    token:
      secret: ${JWT_SECRET}
      expiration: 86400000   # 24 horas em milissegundos
