spring:
  application:
    name: notes-api
  profiles:
    active: dev

logging:
  level:
    org:
      springframework:
        security: DEBUG
    notesapi:
      security: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized